### PR TITLE
fix arturdebil command

### LINKED ISSUE #52: Ban command is not working.
Hi, SXK here,
I can't seem to get the ban command to work. And yes, I checked my grammar. This is the ONLY command that doesn't work.

### PR DESCRIPTION
**Pull request by notSalt**
Fixes #52

### CODE REVIEW

**Review by Madalin-Vis — COMMENTED** [review]
This still doesn't work

**Comment by notSalt** [comment]
Does it return error or nothing happens?

**Comment by TockThomas** [comment]
Nothing happens, he doesn't give an error or something else

**Comment by notSalt** [comment]
Ah, I think I know why it doesn't work.
If you didn't enable Gateway Intents for Server Members, the bot cannot fetch offline or invisible users

**Comment by TockThomas** [comment]
It fixed, thx.

**Comment by notSalt** [comment]
Also, this also should fix #31

**Comment by Madalin-Vis** [comment]
> Ah, I think I know why it doesn't work.
> If you didn't enable Gateway Intents for Server Members, the bot cannot fetch offline or invisible users

 and how do i do that ?

**Comment by notSalt** [comment]
In Discord Developers page, where you create your bot. https://discord.com/developers

**Comment by Madalin-Vis** [comment]
> In Discord Developers page, where you create your bot. https://discord.com/developers

ok...i find it ...but how do i activate it ?

**Comment by Barsik008** [comment]
@notSalt It works, thanks for the fix.

**Comment by notSalt** [comment]
Might also want to close #31 as it's the same issue

**Pull request merged**
